/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_w2v_W2VNative */

#ifndef _Included_com_example_w2v_W2VNative
#define _Included_com_example_w2v_W2VNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_w2v_W2VNative
 * Method:    initEngine
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_w2v_W2VNative_initEngine
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_w2v_W2VNative
 * Method:    loadQAFromFile
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_w2v_W2VNative_loadQAFromFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_example_w2v_W2VNative
 * Method:    loadQAFromMemory
 * Signature: (J[Ljava/lang/String;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_w2v_W2VNative_loadQAFromMemory
  (JNIEnv *, jclass, jlong, jobjectArray, jobjectArray);

/*
 * Class:     com_example_w2v_W2VNative
 * Method:    search
 * Signature: (JLjava/lang/String;)Lcom/example/w2v/W2VNative$SearchResult;
 */
JNIEXPORT jobject JNICALL Java_com_example_w2v_W2VNative_search
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_example_w2v_W2VNative
 * Method:    searchBatch
 * Signature: (J[Ljava/lang/String;)[Lcom/example/w2v/W2VNative$SearchResult;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_w2v_W2VNative_searchBatch
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_example_w2v_W2VNative
 * Method:    getQACount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_w2v_W2VNative_getQACount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_w2v_W2VNative
 * Method:    getEmbeddingDim
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_w2v_W2VNative_getEmbeddingDim
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_w2v_W2VNative
 * Method:    getMemoryUsage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_w2v_W2VNative_getMemoryUsage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_w2v_W2VNative
 * Method:    releaseEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_w2v_W2VNative_releaseEngine
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif